In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [40]:
df = pd.read_csv('../../EDA/data/train.csv', usecols=['Age', 'Sex'])
df

        Sex   Age
0      male  22.0
1    female  38.0
2    female  26.0
3    female  35.0
4      male  35.0
..      ...   ...
886    male  27.0
887  female  19.0
888  female   NaN
889    male  26.0
890    male  32.0

[891 rows x 2 columns]

In [41]:
df = df.dropna()
df.sample(5)

        Sex   Age
871  female  47.0
125    male  12.0
122    male  32.5
610  female  39.0
705    male  39.0

In [42]:
pop = df['Age'].tolist()
pop_mean = np.mean(pop)
pop_mean

np.float64(29.69911764705882)

In [43]:
df.Age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [44]:
pop_male = df[df['Sex'] == 'male']['Age'].tolist()
pop_female = df[df['Sex'] == 'female']['Age'].tolist()

In [45]:
pd.Series(pop_male).isna().sum()
pd.Series(pop_female).isna().sum()

np.int64(0)

In [46]:
# H0: the mean age of male = female (Null hypothesis: there is no significant difference between the mean ages of male and female)
# H1: the mean age of male > female (Altenative hypothesis is one tailed)

sample_male = np.random.choice(pop_male, size=25, replace=False)
sample_female = np.random.choice(pop_female, size=25, replace=False)
alpha = 0.05

In [47]:
from scipy.stats import shapiro, levene, ttest_ind

shapiro_result_male = shapiro(sample_male)
shapiro_result_female = shapiro(sample_female)
print("Shapiro-Wilk test for male sample:", shapiro_result_male)
print("Shapiro-Wilk test for female sample:", shapiro_result_female)

Shapiro-Wilk test for male sample: ShapiroResult(statistic=np.float64(0.9819802208170477), pvalue=np.float64(0.9213264028594709))
Shapiro-Wilk test for female sample: ShapiroResult(statistic=np.float64(0.9128024795582355), pvalue=np.float64(0.03521623026401746))

shapiro values of male and female > alpha (0.05): so the sample is normal

In [48]:
levene_test = levene(sample_male, sample_female)
print("Levene's test for equality of variances:", levene_test)

Levene's test for equality of variances: LeveneResult(statistic=np.float64(1.0089874051213603), pvalue=np.float64(0.32018261513358964))

p_value > 0.05(alpha): so the two samples have no significance differnce in varience

In [49]:
t_stats, p_value = ttest_ind(sample_male, sample_female)
print("T-test statistic:", t_stats)
print("P-value:", p_value)

T-test statistic: 1.5611509626041802
P-value: 0.12505783006446766

In [50]:
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: there is a significant difference in mean ages between male and female")
else:
    print("Fail to reject the null hypothesis: there is no significant difference in mean ages between male and female")

Fail to reject the null hypothesis: there is no significant difference in mean ages between male and female